import { chmod, mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { homedir, userInfo } from "node:os";
import { dirname, isAbsolute, join, resolve } from "node:path";

import { type CommandRunner, requireSuccess, runCommand } from "./command.ts";
import { loadConfig } from "./config.ts";
import {
  currentServiceUnitPaths,
  installedUnitPaths,
  NOT_INSTALLED,
  serviceProgramArguments,
  serviceProgramPaths,
  type ServiceUnitPaths,
  type ServiceUnitState,
  unitStateFor,
} from "./service-unit.ts";

export const AGENT_TAG_SYSTEMD_UNIT = "agent-tag.service";

export type SystemdUnitDefinition = ServiceUnitPaths;

export interface SystemdServiceStatus {
  readonly manager: "systemd";
  readonly unit: string;
  readonly unitPath: string;
  readonly installed: boolean;
  readonly loaded: boolean;
  readonly enabled: boolean;
  readonly running: boolean;
  readonly hints: readonly string[];
}

export type SystemdUnitState = ServiceUnitState;

function assertUnitPath(path: string): void {
  if (!isAbsolute(path)) throw new Error("systemd unit paths must be absolute");
  // Control characters would split or corrupt the unit file line.
  if (/[\u0000-\u001f\u007f]/.test(path)) throw new Error("systemd unit paths must not contain control characters");
}

/** Escapes one ExecStart argument: systemd specifiers (%), variable expansion ($), quotes and backslashes. */
export function systemdQuote(argument: string): string {
  const escaped = argument
    .replaceAll("\\", "\\\\")
    .replaceAll('"', '\\"')
    .replaceAll("%", "%%")
    .replaceAll("$", "$$$$");
  return `"${escaped}"`;
}

function systemdPathValue(path: string): string {
  return path.replaceAll("%", "%%");
}

/** Reverses `systemdQuote` for one argument body (without the surrounding quotes). */
function systemdUnquote(body: string): string {
  let result = "";
  for (let index = 0; index < body.length; index += 1) {
    const character = body[index]!;
    const next = body[index + 1];
    if (character === "\\" && next !== undefined) {
      result += next;
      index += 1;
    } else if ((character === "%" || character === "$") && next === character) {
      result += character;
      index += 1;
    } else {
      result += character;
    }
  }
  return result;
}

/** Reads ExecStart arguments and WorkingDirectory back out of an installed unit. */
export function parseSystemdUnitPaths(unit: string): Partial<ServiceUnitPaths> {
  const execStart = /^ExecStart=(.*)$/m.exec(unit)?.[1] ?? "";
  const programArguments = [...execStart.matchAll(/"((?:[^"\\]|\\.)*)"/g)].map((match) => systemdUnquote(match[1] ?? ""));
  const workingDirectory = /^WorkingDirectory=(.*)$/m.exec(unit)?.[1]?.replaceAll("%%", "%");
  return installedUnitPaths(programArguments, workingDirectory);
}

export function renderSystemdUnit(input: SystemdUnitDefinition): string {
  for (const path of [...serviceProgramPaths(input.program), input.configPath, input.workingDirectory]) {
    assertUnitPath(path);
  }
  const execStart = serviceProgramArguments(input.program, "run", input.configPath)
    .map(systemdQuote)
    .join(" ");
  return `# Generated by agent-tag. Regenerate with: agent-tag service upgrade CONFIG
[Unit]
Description=Agent Tag Slack coworker
Documentation=https://github.com/Dhruv2mars/agent-tag/blob/main/docs/operations.md
# A --user manager cannot order against system targets such as network-online.target.
# Never give up restarting: agent-tag run exits while T3 is down, and launchd KeepAlive also retries forever.
StartLimitIntervalSec=0

[Service]
Type=simple
WorkingDirectory=${systemdPathValue(input.workingDirectory)}
ExecStart=${execStart}
Restart=always
RestartSec=10
KillSignal=SIGTERM
TimeoutStopSec=60
UMask=0077
NoNewPrivileges=true

[Install]
WantedBy=default.target
`;
}

/** Parses `systemctl show --property=...` key=value output. */
export function parseSystemctlShow(output: string): ReadonlyMap<string, string> {
  const values = new Map<string, string>();
  for (const line of output.split("\n")) {
    const separator = line.indexOf("=");
    if (separator > 0) values.set(line.slice(0, separator).trim(), line.slice(separator + 1).trim());
  }
  return values;
}

export function lingerHint(loginctlOutput: string, user: string): string | undefined {
  const linger = parseSystemctlShow(loginctlOutput).get("Linger");
  if (linger === "yes") return undefined;
  return `user lingering is not enabled; run \`loginctl enable-linger ${user}\` so the service starts at boot and keeps running after logout`;
}

export function systemdLogsCommand(input: { readonly lines: number; readonly follow: boolean }): string[] {
  return [
    "journalctl",
    "--user",
    "--unit",
    AGENT_TAG_SYSTEMD_UNIT,
    "--lines",
    String(input.lines),
    "--no-pager",
    ...(input.follow ? ["--follow"] : []),
  ];
}

export interface SystemdHost {
  readonly run: CommandRunner;
  readonly unitDirectory: string;
  readonly user: string;
  readonly sleep: (milliseconds: number) => Promise<void>;
  readonly definition: (configPath: string) => Promise<SystemdUnitDefinition>;
  /** Runs the doctor against the definition before the unit changes; throws on failure. */
  readonly preflight: (definition: SystemdUnitDefinition) => Promise<void>;
}

function systemctl(...args: string[]): string[] {
  return ["systemctl", "--user", ...args];
}

async function writeUnitFile(path: string, content: string): Promise<void> {
  const temporaryPath = join(dirname(path), `.${AGENT_TAG_SYSTEMD_UNIT}.${crypto.randomUUID()}.tmp`);
  try {
    await writeFile(temporaryPath, content, { encoding: "utf8", mode: 0o600, flag: "wx" });
    await chmod(temporaryPath, 0o600);
    await rename(temporaryPath, path);
  } finally {
    await rm(temporaryPath, { force: true });
  }
}

async function readOptional(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  }
}

export class SystemdUserService {
  readonly #host: SystemdHost;

  constructor(host: SystemdHost) {
    this.#host = host;
  }

  get unitPath(): string {
    return join(this.#host.unitDirectory, AGENT_TAG_SYSTEMD_UNIT);
  }

  /**
   * Reads the unit's runtime state. `systemctl show` succeeds with `LoadState=not-found` for an absent unit,
   * so a non-zero exit means the user manager itself is unreachable. With `strict`, that throws instead of
   * being reported as an unloaded unit.
   */
  async #runtime(strict = false): Promise<{ readonly loaded: boolean; readonly enabled: boolean; readonly running: boolean }> {
    const result = await this.#host.run(
      systemctl("show", AGENT_TAG_SYSTEMD_UNIT, "--property=LoadState,ActiveState,SubState,UnitFileState"),
    );
    if (result.exitCode !== 0) {
      if (strict) {
        throw new Error(
          `systemd show failed with exit code ${result.exitCode}: ${result.stderr.trim()}; ` +
            `could not confirm the service is stopped, so kept ${this.unitPath}`,
        );
      }
      return { loaded: false, enabled: false, running: false };
    }
    const values = parseSystemctlShow(result.stdout);
    return {
      loaded: values.get("LoadState") === "loaded",
      enabled: values.get("UnitFileState") === "enabled",
      running: values.get("ActiveState") === "active" && values.get("SubState") === "running",
    };
  }

  async #waitUntilRunning(): Promise<boolean> {
    for (let attempt = 0; attempt < 100; attempt += 1) {
      if ((await this.#runtime()).running) return true;
      await this.#host.sleep(100);
    }
    return false;
  }

  async #hints(): Promise<string[]> {
    const result = await this.#host.run([
      "loginctl",
      "show-user",
      this.#host.user,
      "--property=Linger",
    ]);
    if (result.exitCode !== 0) {
      return [`could not read lingering state; run \`loginctl enable-linger ${this.#host.user}\` to keep the service running after logout`];
    }
    const hint = lingerHint(result.stdout, this.#host.user);
    return hint === undefined ? [] : [hint];
  }

  async status(): Promise<SystemdServiceStatus> {
    const runtime = await this.#runtime();
    return {
      manager: "systemd",
      unit: AGENT_TAG_SYSTEMD_UNIT,
      unitPath: this.unitPath,
      installed: (await readOptional(this.unitPath)) !== undefined,
      loaded: runtime.loaded,
      enabled: runtime.enabled,
      running: runtime.running,
      hints: await this.#hints(),
    };
  }

  async unitState(configPath: string): Promise<SystemdUnitState> {
    const existing = await readOptional(this.unitPath);
    if (existing === undefined) return { unitPath: this.unitPath, ...NOT_INSTALLED };
    const definition = await this.#host.definition(configPath);
    return unitStateFor({
      unitPath: this.unitPath,
      existing,
      rendered: renderSystemdUnit(definition),
      installed: parseSystemdUnitPaths(existing),
      expected: definition,
    });
  }

  /** Clears a failed state (including a start-limit hit) so the next start is not refused. */
  async #resetFailed(): Promise<void> {
    await this.#host.run(systemctl("reset-failed", AGENT_TAG_SYSTEMD_UNIT));
  }

  async #enableAndStart(description: string): Promise<void> {
    await requireSuccess(this.#host.run, systemctl("daemon-reload"), "systemd daemon-reload");
    await this.#resetFailed();
    await requireSuccess(this.#host.run, systemctl("enable", "--now", AGENT_TAG_SYSTEMD_UNIT), description);
    if (!(await this.#waitUntilRunning())) throw new Error("systemd unit did not reach running state");
  }

  async install(configPath: string): Promise<SystemdServiceStatus> {
    if ((await readOptional(this.unitPath)) !== undefined) {
      throw new Error("Agent Tag systemd unit is already installed; use `agent-tag service upgrade`");
    }
    const definition = await this.#host.definition(configPath);
    await this.#host.preflight(definition);
    await mkdir(this.#host.unitDirectory, { recursive: true });
    await writeUnitFile(this.unitPath, renderSystemdUnit(definition));
    try {
      await this.#enableAndStart("systemd enable");
    } catch (error) {
      await this.#host.run(systemctl("disable", "--now", AGENT_TAG_SYSTEMD_UNIT));
      await rm(this.unitPath, { force: true });
      await this.#host.run(systemctl("daemon-reload"));
      throw error;
    }
    return this.status();
  }

  async upgrade(configPath: string): Promise<SystemdServiceStatus> {
    const prior = await readOptional(this.unitPath);
    if (prior === undefined) throw new Error("Agent Tag systemd unit is not installed");
    const definition = await this.#host.definition(configPath);
    await this.#host.preflight(definition);
    const wasRunning = (await this.#runtime()).running;
    await writeUnitFile(this.unitPath, renderSystemdUnit(definition));
    try {
      await requireSuccess(this.#host.run, systemctl("daemon-reload"), "systemd daemon-reload");
      await requireSuccess(this.#host.run, systemctl("enable", AGENT_TAG_SYSTEMD_UNIT), "systemd enable");
      await this.#resetFailed();
      await requireSuccess(this.#host.run, systemctl("restart", AGENT_TAG_SYSTEMD_UNIT), "systemd restart");
      if (!(await this.#waitUntilRunning())) throw new Error("systemd unit did not reach running state");
    } catch (error) {
      await writeUnitFile(this.unitPath, prior);
      await this.#host.run(systemctl("daemon-reload"));
      await this.#resetFailed();
      if (!wasRunning) {
        await this.#host.run(systemctl("stop", AGENT_TAG_SYSTEMD_UNIT));
        throw error;
      }
      const rollback = await this.#host.run(systemctl("restart", AGENT_TAG_SYSTEMD_UNIT));
      if (rollback.exitCode !== 0) {
        const message = error instanceof Error ? error.message : String(error);
        throw new Error(`${message}; restarting the prior unit also failed: ${rollback.stderr}`);
      }
      throw error;
    }
    return this.status();
  }

  async restart(): Promise<SystemdServiceStatus> {
    if ((await readOptional(this.unitPath)) === undefined) {
      throw new Error("Agent Tag systemd unit is not installed");
    }
    await this.#resetFailed();
    await requireSuccess(this.#host.run, systemctl("restart", AGENT_TAG_SYSTEMD_UNIT), "systemd restart");
    if (!(await this.#waitUntilRunning())) throw new Error("systemd unit did not reach running state");
    return this.status();
  }

  async uninstall(): Promise<SystemdServiceStatus> {
    if ((await this.#runtime(true)).loaded) {
      // Keep the unit file when systemd could not stop it, so the operator can fix the cause and retry.
      const disabled = await this.#host.run(systemctl("disable", "--now", AGENT_TAG_SYSTEMD_UNIT));
      if (disabled.exitCode !== 0) {
        throw new Error(
          `systemd disable --now failed with exit code ${disabled.exitCode}: ${disabled.stderr.trim()}; ` +
            `kept ${this.unitPath} so you can retry \`agent-tag service uninstall\``,
        );
      }
    }
    await rm(this.unitPath, { force: true });
    await requireSuccess(this.#host.run, systemctl("daemon-reload"), "systemd daemon-reload");
    await this.#host.run(systemctl("reset-failed", AGENT_TAG_SYSTEMD_UNIT));
    return this.status();
  }

  logsCommand(input: { readonly lines: number; readonly follow: boolean }): string[] {
    return systemdLogsCommand(input);
  }
}

export function systemdUnitDirectory(env: Record<string, string | undefined> = Bun.env): string {
  const configHome = env.XDG_CONFIG_HOME;
  const base = configHome !== undefined && isAbsolute(configHome) ? configHome : join(homedir(), ".config");
  return join(base, "systemd", "user");
}

export async function systemdUnitDefinition(configPathInput: string): Promise<SystemdUnitDefinition> {
  const configPath = resolve(configPathInput);
  await loadConfig(configPath);
  return currentServiceUnitPaths(configPath);
}

export function createSystemdUserService(): SystemdUserService {
  if (process.platform !== "linux") throw new Error("systemd management is supported only on Linux");
  return new SystemdUserService({
    run: runCommand,
    unitDirectory: systemdUnitDirectory(),
    user: userInfo().username,
    sleep: (milliseconds) => Bun.sleep(milliseconds),
    definition: systemdUnitDefinition,
    preflight: async (definition) => {
      await requireSuccess(
        runCommand,
        serviceProgramArguments(definition.program, "doctor", definition.configPath),
        "Agent Tag doctor",
      );
    },
  });
}
